baseURL = ""
languageCode = "en-us"
title = "Hadi Hidayat Hammurabi"
subtitle = "Hammurabi Personal Documents"
theme = "m10c"

disqusShortname= "hadihammurabi"

[params.author]
name = "Hadi Hidayat Hammurabi"

[[params.social]]
  name = "github"
  url = "https://github.com/hadihammurabi"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/hadihammurabi"

[[params.social]]
  name = "youtube"
  url = "https://youtube.com/c/tamankodekode"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/hadihammurabi"

[[params.social]]
  name = "instagram"
  url = "http://instagram.com/hadihammurabi"

[[params.social]]
  name = "website"
  url = "http://tamankodekode.com"

[params.style]
  #darkestColor = "#181F28"
  darkColor = "#212121"
  #lightColor = "#f5e3e0"
  #lightestColor = "#f5f5f5"
  primaryColor = "#0277BD"
