baseURL = "http://localhost:8080"
languageCode = "en-us"
title = "Hadi Hidayat Hammurabi"
subtitle = "Hadi Hidayat Hammurabi"
theme = "m10c"

author = "Hadi Hidayat Hammurabi"

[[params.social]]
  name = "github"
  url = "https://github.com/hadihammurabi"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/hadihammurabi"

[[params.social]]
  name = "youtube"
  url = "https://youtube.com/c/tamankodekode"

[params.style]
  #darkestColor = "#181F28"
  darkColor = "#212121"
  #lightColor = "#f5e3e0"
  #lightestColor = "#f5f5f5"
  primaryColor = "#47f"
